name: Lint OpenAPI in IKEA API Gateway

on:
  workflow_dispatch:
  push:
    paths:
      - <spec-files-path>

jobs:
  lint-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint OpenAPI specifications
        uses: ingka-group-digital/lint-openapi@v1.0.1
        with:
          github_url: https://raw.git.build.ingka.ikea.com/Sales-Order-Fulfilment/ISOMOFD-S10/master/SOM-API/IKEAGetOrderInfo.yaml?token=GHSAT0AAAAAAAAANT75TQJD5TNXNGWBUJYIZJ2NNVQ
          files: |
            examples/IKEAGetOrderInfo.yaml
          shouldApplyGatewayRules: true
